[build]
  publish = "."
  command = "echo 'PHP Application - No build step required'"

[build.environment]
  PHP_VERSION = "8.1"

# Handle PHP files
[functions]
  directory = "functions/"

# Redirect all requests to index.php for PHP routing
[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment variables (these will need to be set in Netlify dashboard)
[build.processing]
  skip_processing = false
