# Railway Deployment Configuration
# Place this in your Railway project settings

# Build Configuration
[build]
builder = "php"
phpVersion = "8.1"

# Environment Variables (set these in Railway dashboard)
[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://your-app.railway.app"

# Database Configuration (Railway will provide these)
DB_CONNECTION = "mysql"
DB_HOST = "your-mysql-host"
DB_PORT = "3306"
DB_DATABASE = "railway"
DB_USERNAME = "root"
DB_PASSWORD = "your-password"

# Session Configuration
SESSION_LIFETIME = "120"
SESSION_SECURE_COOKIE = "true"

# Security
APP_KEY = "your-generated-app-key"

# Instructions:
# 1. Railway will auto-detect this is a PHP app
# 2. It will automatically set up MySQL database
# 3. Set the environment variables above in Railway dashboard
# 4. Your app will deploy automatically from GitHub
