# Railway PHP Application Configuration
# This file tells Railway how to build and deploy your PHP app

[build]
# Railway will auto-detect PHP applications
# No specific builder configuration needed

[deploy]
# Railway handles deployment automatically
# Environment variables are set in the Railway dashboard

# Railway automatically provides:
# - PHP runtime (latest version)
# - MySQL database
# - Environment variables
# - SSL certificates

# Instructions:
# 1. Railway auto-detects this as a PHP app
# 2. MySQL database is created automatically
# 3. Set environment variables in Railway dashboard
# 4. Deployment happens automatically
